dist: trusty
language: python
python:
  - "3.6"
services:
  - docker
cache:
  directories:
    - /tmp/sc-docker
before_install:
  - jdk_switcher use oraclejdk8
before_script:
  - git clone https://github.com/Bytekeeper/sc-docker.git
  - pushd sc-docker
  - pip3 install numpy==1.16.6
  - python3 setup.py bdist_wheel
  - pip3 install dist/scbw*.whl
  - '[ ! -f /tmp/sc-docker/starcraft.zip ] || (cp /tmp/sc-docker/starcraft.zip scbw/local_docker && echo "Using cached starcraft.zip")'
  - cd docker
  - ./build_images.sh
  - popd
  - "[ -f /tmp/sc-docker/starcraft.zip ] || cp sc-docker/scbw/local_docker/starcraft.zip /tmp/sc-docker/starcraft.zip"
  - scbw.play --install
script:
  - sh mvnw clean install
  - sh mvnw -f it/bots/pom.xml package
  - for bot in $(ls -d it/bots/*/); do BOTNAME=$(basename $bot); echo "Setting up $BOTNAME"; mkdir -p "$HOME/.scbw/bots/$BOTNAME/AI" "$HOME/.scbw/bots/$BOTNAME/read" "$HOME/.scbw/bots/$BOTNAME/write"; cp it/sc-docker-support/BWAPI.dll "$HOME/.scbw/bots/$BOTNAME"; cp "$bot/target/"*-with-dependencies.jar "$HOME/.scbw/bots/$BOTNAME/AI"; cp "$bot/bot.json" "$HOME/.scbw/bots/$BOTNAME"; done
  - scbw.play --headless --bots jbwapibot SittingDuck --timeout 180 --docker_image starcraft:game 2>&1 | grep 'Winner is BotPlayer:jbwapibot:T' || (cat $HOME/.scbw/games/*/logs_0/* && false)
